services:
  db:
    image: mysql:8.0
    container_name: pi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: gestion_reservas
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuario
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d:ro 

    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: pi-backend
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/gestion_reservas?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: usuario
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: pi-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pi-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - db
    restart: always

volumes:
  db_data:
